version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '81:81'
      - '443:443'
    network_mode: <docker network>

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
