version: '3.8'
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Warsaw
    volumes:
      - './config:/config'
    restart: unless-stopped
    network_mode: <docker network>
