version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - DOCKER_MTU=1500 #optional
    volumes:
      - './opt:/opt'
      - './profiles:/profiles' #optional
    network_mode: <docker network>
    restart: unless-stopped
