version: '3.3'
services:
  portainer:
    network_mode: <docker network>
    restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data:/data'
    image: portainer/portainer-ce
